"""add form last_comment fields

Revision ID: 0ce4c4ad88fb
Revises: 0ea7e9955578
Create Date: 2026-01-28 20:25:37.822533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce4c4ad88fb'
down_revision: Union[str, Sequence[str], None] = '0ea7e9955578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('last_comment', sa.Text(), nullable=True))
    op.add_column('forms', sa.Column('last_commented_by_role', sa.String(length=30), nullable=True))
    op.add_column('forms', sa.Column('last_commented_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'last_commented_at')
    op.drop_column('forms', 'last_commented_by_role')
    op.drop_column('forms', 'last_comment')
    # ### end Alembic commands ###
