"""add forms and collection window

Revision ID: 0ea7e9955578
Revises: 1f147dcc5f90
Create Date: 2026-01-28 15:04:34.883280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea7e9955578'
down_revision: Union[str, Sequence[str], None] = '1f147dcc5f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_area_id'), 'forms', ['area_id'], unique=False)
    op.create_index(op.f('ix_forms_cost_center_id'), 'forms', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_forms_created_by_user_id'), 'forms', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_forms_status'), 'forms', ['status'], unique=False)
    op.create_table('form_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('training_category_id', sa.Integer(), nullable=False),
    sa.Column('training_name_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('quarter', sa.String(length=2), nullable=False),
    sa.Column('business_need_id', sa.Integer(), nullable=False),
    sa.Column('employees_count', sa.Integer(), nullable=False),
    sa.Column('employee_full_name', sa.String(length=200), nullable=True),
    sa.Column('estimated_cost_per_person', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_hours_per_person', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hr_budget_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['business_need_id'], ['business_needs.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['training_category_id'], ['training_categories.id'], ),
    sa.ForeignKeyConstraint(['training_name_id'], ['training_names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_items_business_need_id'), 'form_items', ['business_need_id'], unique=False)
    op.create_index(op.f('ix_form_items_form_id'), 'form_items', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_items_training_category_id'), 'form_items', ['training_category_id'], unique=False)
    op.create_index(op.f('ix_form_items_training_name_id'), 'form_items', ['training_name_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_items_training_name_id'), table_name='form_items')
    op.drop_index(op.f('ix_form_items_training_category_id'), table_name='form_items')
    op.drop_index(op.f('ix_form_items_form_id'), table_name='form_items')
    op.drop_index(op.f('ix_form_items_business_need_id'), table_name='form_items')
    op.drop_table('form_items')
    op.drop_index(op.f('ix_forms_status'), table_name='forms')
    op.drop_index(op.f('ix_forms_created_by_user_id'), table_name='forms')
    op.drop_index(op.f('ix_forms_cost_center_id'), table_name='forms')
    op.drop_index(op.f('ix_forms_area_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_table('collection_windows')
    # ### end Alembic commands ###
