"""add dictionaries

Revision ID: 1f147dcc5f90
Revises: f8c1ca882ce1
Create Date: 2026-01-28 14:24:26.817508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f147dcc5f90'
down_revision: Union[str, Sequence[str], None] = 'f8c1ca882ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_pl', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_code'), 'areas', ['code'], unique=True)
    op.create_table('business_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_pl', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_pl', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_pl', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_centers_area_id'), 'cost_centers', ['area_id'], unique=False)
    op.create_index(op.f('ix_cost_centers_code'), 'cost_centers', ['code'], unique=False)
    op.create_table('training_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name_pl', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['training_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_names_category_id'), 'training_names', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_names_category_id'), table_name='training_names')
    op.drop_table('training_names')
    op.drop_index(op.f('ix_cost_centers_code'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_area_id'), table_name='cost_centers')
    op.drop_table('cost_centers')
    op.drop_table('training_categories')
    op.drop_table('business_needs')
    op.drop_index(op.f('ix_areas_code'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
