"""add user.area_id for manager scoping

Revision ID: 71bd40ba6427
Revises: e5a965ac55e8
Create Date: 2026-01-29 10:42:00.736263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bd40ba6427'
down_revision: Union[str, Sequence[str], None] = 'e5a965ac55e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_area_id'), 'users', ['area_id'], unique=False)
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_area_id'), table_name='users')
    op.drop_column('users', 'area_id')
    # ### end Alembic commands ###
