"""update form models for workflow

Revision ID: b7b85b1e6631
Revises: 1d733089ac4a
Create Date: 2026-02-07 16:18:00.555497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b85b1e6631'
down_revision: Union[str, Sequence[str], None] = '1d733089ac4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_areas_area_id'), table_name='user_areas')
    op.drop_index(op.f('ix_user_areas_user_id'), table_name='user_areas')
    op.drop_table('user_areas')
    op.add_column('form_items', sa.Column('hr_comments', sa.Text(), nullable=True))
    op.add_column('forms', sa.Column('collection_window_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_forms_collection_window_id'), 'forms', ['collection_window_id'], unique=False)
    op.create_foreign_key(None, 'forms', 'collection_windows', ['collection_window_id'], ['id'])
    #op.create_unique_constraint('uq_user_area_access', 'user_area_access', ['user_id', 'area_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_area_access', 'user_area_access', type_='unique')
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_index(op.f('ix_forms_collection_window_id'), table_name='forms')
    op.drop_column('forms', 'collection_window_id')
    op.drop_column('form_items', 'hr_comments')
    op.create_table('user_areas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('user_areas_area_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_areas_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_areas_pkey')),
    sa.UniqueConstraint('user_id', 'area_id', name=op.f('uq_user_areas_user_area'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_areas_user_id'), 'user_areas', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_areas_area_id'), 'user_areas', ['area_id'], unique=False)
    # ### end Alembic commands ###
