"""add form_events

Revision ID: e5a965ac55e8
Revises: 0ce4c4ad88fb
Create Date: 2026-01-29 08:40:15.332035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a965ac55e8'
down_revision: Union[str, Sequence[str], None] = '0ce4c4ad88fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_events_action'), 'form_events', ['action'], unique=False)
    op.create_index(op.f('ix_form_events_actor_user_id'), 'form_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_form_events_form_id'), 'form_events', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_events_item_id'), 'form_events', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_events_item_id'), table_name='form_events')
    op.drop_index(op.f('ix_form_events_form_id'), table_name='form_events')
    op.drop_index(op.f('ix_form_events_actor_user_id'), table_name='form_events')
    op.drop_index(op.f('ix_form_events_action'), table_name='form_events')
    op.drop_table('form_events')
    # ### end Alembic commands ###
